name: Docker Image CI

on:
  label:
    types: [created]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
    - run: docker build . --file Dockerfile --tag hestudio/bingwallpaper_get:${GITHUB_REF}
    - run: docker build . --file Dockerfile --tag hestudio/bingwallpaper_get
    - run: docker push hestudio/bingwallpaper_get:${GITHUB_REF}
    - run: docker push hestudio/bingwallpaper_get
    
