name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:

  build:

    runs-on: ubuntu-latest
    name:  Build Docker Image
    steps:
    - uses: actions/checkout@v3
    - run: docker login --username hestudio --password ${{ secrets.DOCKER_PASSWORD }}
    - run: docker build . --file Dockerfile --tag hestudio/bingwallpaper_get:${{ github.REF }}
    - run: docker build . --file Dockerfile --tag hestudio/bingwallpaper_get
    - run: docker push hestudio/bingwallpaper_get:${{ github.REF }}
    - run: docker push hestudio/bingwallpaper_get
    
