name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  build:

    runs-on: ubuntu-latest
    name:  Build Docker Image
    steps:
    - uses: actions/checkout@v3
    - name: Get version
      id: get_version
      run: echo "::set-output name=tag::$(echo "${{ github.REF }}" | sed -e 's|^refs/tags/||')"
    - name: Login Docker
      run: docker login --username hestudio --password ${{ secrets.DOCKER_PASSWORD }}
    - run: docker build . --file Dockerfile --tag hestudio/bingwallpaper_get:${{ steps.get_version.outputs.tag }}
    - run: docker build . --file Dockerfile --tag hestudio/bingwallpaper_get
    - run: docker push hestudio/bingwallpaper_get:${{ steps.get_version.outputs.tag }}
    - run: docker push hestudio/bingwallpaper_get
    
